close issue #3 explain and ask for config on first use
facundobatista/recordium pull request #12
Opened 2017-01-07 14:59 UTC by marian-vignau

#3 on first run, program ask for configuration

2017-01-07 18:14 UTC, facundobatista requested changes
A couple of details...

2017-01-07 18:14 UTC, facundobatista commented on recordium/main.py
> +        if config.get(config.BOT_AUTH_TOKEN):
No matter if the user configured something or not, the app should start as usual, so remove this "if" and let the app just start

2017-01-07 18:14 UTC, facundobatista commented on recordium/main.py
> +            """Start application network and systray menu & icon"""
This string sould be a comment

2017-01-07 18:53 UTC, marian-vignau commented
done... see it pls

2017-01-09 11:55 UTC, facundobatista commented
You did a change for good and another for bad :/

- For good: it's great that everytime you go to the config, and the token is not configured, you see the message

- For bad: you changed something that was GREAT in the previous version of your code: that when you start the program and the token is not configured, the config window is opened to you.

So, please restore the wonderful thing you did before of opening the config dialog on start if the token wasn't there (note that when the user closes that config, no matter if it's well configured or not, the program just should continue ok).

2017-01-09 13:19 UTC, marian-vignau commented
done

2017-01-09 17:01 UTC, merged

2017-01-09 17:02 UTC, facundobatista commented
Wonderful, thanks!