Adapted to Windows and create an installer
facundobatista/recordium pull request #16
Opened 2017-01-11 14:37 UTC by marian-vignau

2017-01-13 12:07 UTC, facundobatista requested changes
I included some comments in the diff.

Also, please include a "build_instructions.txt " file in the windows directory with all the steps to build the installer.

Thanks!!!

2017-01-13 12:07 UTC, facundobatista commented on .gitignore
> +Setup.exe
with the S in uppercase?

2017-01-13 12:07 UTC, facundobatista commented on bin/recordium
> +    os.chdir(parent_dir) #to allow use of relative paths
to allow use relative paths where?

2017-01-13 12:07 UTC, facundobatista commented on recordium/main.py
> -
don't remove this line, it separates normal and "from" imports

2017-01-13 12:07 UTC, facundobatista commented on recordium/main.py
> +def add_envirom():
it's "environ", not "envirom"; also I'd use a name like "fix_environment"

2017-01-13 12:07 UTC, facundobatista commented on recordium/main.py
> +    import PyQt5
Put these imports at top level, as the others

2017-01-13 12:07 UTC, facundobatista commented on recordium/main.py
> +            QtWidgets.QMessageBox.information(
What? This is a leftover from the past?

2017-01-13 12:07 UTC, facundobatista commented on recordium/utils.py
> +config_basedir = app.user_config_dir
Note that we're changing the config directory here; so if a user has already configured system, you will be missing that original file.

So, if you want to change the directory here, you should move the original file in.

2017-01-13 12:07 UTC, facundobatista commented on recordium/utils.py
> +                app.user_data_dir]:
All these fit in the column limit, don't wrap.

Also, for a fixed lenght list, just use a tuple.

2017-01-13 12:07 UTC, facundobatista commented on run
> +fades --system-site-packages -r requirements.txt bin/recordium $@
Why this change?

2017-01-13 12:07 UTC, facundobatista commented on windows/install.nsi
> +!define MUI_ICON "..\media\recordium.ico"
this file should be included in the project

2017-01-19 19:55 UTC, marian-vignau commented on .gitignore
> +Setup.exe
To avoid include in source control the compiled installer. 
It is the default name that NSIS gives to new installers.

2017-01-19 19:57 UTC, marian-vignau commented on bin/recordium
> +    os.chdir(parent_dir) #to allow use of relative paths
When the software is runned from development, it can't find media icons because current directory is not correct. I fixed it

2017-02-03 01:36 UTC, facundobatista requested changes

2017-02-03 01:36 UTC, facundobatista commented on recordium/main.py
> +import PyQt5
This import should be below, between the "from functools..." and the "from PyQt5 ones..." (separated with a blank line from both)

2017-02-03 01:36 UTC, facundobatista commented on recordium/main.py
> +    '''add enviroment variable on Windows systems'''
The rules for docstrings say this should be: ` """Add enviroment variable on Windows systems."""`

2017-02-03 01:36 UTC, facundobatista commented on recordium/main.py
> +ICONPATH_PROBLEM = 'media/icon-problem-192.png'
this change is already in master... bad merge?

2017-02-03 01:36 UTC, facundobatista commented on recordium/utils.py
> +    prev_cfg = os.path.join(os.path.split(app.user_config_dir)[0], config_file_name)
The `os.path.split(...)[0]` is simpler and less confusing doing `os.path.dirname(app.user_config_dir)`

2017-02-08 14:26 UTC, facundobatista commented
Summary of details:

1. En los docstrings, siempre arrancá con mayúscula (corregí el "add") y siempre terminá con punto (a las dos docstrings le falta)
2. metiste una linea en blanco al cuete (en bin/recordium) luego de los imports
3. sigue habiendo problemas de merge (veo como que metés el media/icon-problem-192.png , por ejemplo)
4. en recordium/main.py metiste los import sin respetar orden alfabético
5. sigue habiendo un cambio inexplicable en el "run"

2017-02-19 02:44 UTC, closed without merging