enable user to configurate column order
facundobatista/recordium pull request #24
Opened 2017-05-14 01:02 UTC by marian-vignau

2017-05-16 20:50 UTC, facundobatista commented on recordium/config.py
> +        'COL_ORDER': '2, 0, 1, 3'
Why not have a list with ints here? it will simplify the code elsewhere...

Also, default order should be what's current choice.

2017-05-16 22:52 UTC, marian-vignau commented on recordium/config.py
> +        'COL_ORDER': '2, 0, 1, 3'
Of course! You use pickle! Thanks

2017-05-21 13:10 UTC, facundobatista requested changes
This is improving! There are two small details, and something new to consider that we need to think of...

2017-05-21 13:10 UTC, facundobatista commented on recordium/main.py
> +        col_order = [int(i) for i in config.get(config.COL_ORDER)]
No need to do int() if you already store an integer...

2017-05-21 13:10 UTC, facundobatista commented on recordium/main.py
> +        for col in range(0, self.columnCount()):
no need to start the range() with 0, it's the default, you can skip it

2017-05-21 13:10 UTC, facundobatista commented on recordium/main.py
> +            col_order.append(str(self.visualColumn(col)))
Don't do str() on the number, just store the int!

2017-05-21 13:10 UTC, facundobatista commented on recordium/main.py
> +        config.save()
We shouldn't be touching disk *always* here. 

Most probably, 99.9999999% of the cases the user will not change this config, so hitting disk everytime seems like a huge waste here.

What you could do is to compare the current order with the configured one; if different, save it. Other thing that you could do (but didn't explored it myself) would be to hook into a signal for the "columns order changed" situation, have an internal flag about this, and if that flag is set, save the config)

2017-05-21 20:11 UTC, marian-vignau commented on recordium/main.py
> +        col_order = [int(i) for i in config.get(config.COL_ORDER)]
Yes

2017-05-21 20:16 UTC, marian-vignau commented on recordium/main.py
> +            col_order.append(str(self.visualColumn(col)))
Ok

2017-05-31 22:47 UTC, facundobatista requested changes
Added one comment that was the same from last review. Please address all comments on each proposal, thanks!

2017-05-31 22:47 UTC, facundobatista commented on recordium/main.py
> +        config.save()
As I said in the last review: We shouldn't be touching disk always here.

Most probably, 99.9999999% of the cases the user will not change this config, so hitting disk everytime seems like a huge waste here.

What you could do is to compare the current order with the configured one; if different, save it. Other thing that you could do (but didn't explored it myself) would be to hook into a signal for the "columns order changed" situation, have an internal flag about this, and if that flag is set, save the config)

2017-06-02 17:42 UTC, merged

2017-06-02 17:42 UTC, facundobatista commented
Great, thanks!!!